apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-test1
spec:
  selector:
    matchLabels:
      app: graphql-test1
  template:
    metadata:
      labels:
        app: graphql-test1
    spec:
      containers:
        - name: graphql-test1
          image: 179172241320.dkr.ecr.ap-south-1.amazonaws.com/graphql-test1:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-test1
spec:
  selector:
    app: graphql-test1
  ports:
    - port: 80
      targetPort: 8081
