apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-test2
spec:
  selector:
    matchLabels:
      app: rest-test2
  template:
    metadata:
      labels:
        app: rest-test2
    spec:
      containers:
        - name: rest-test2
          image: 179172241320.dkr.ecr.ap-south-1.amazonaws.com/rest-test2:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rest-test2
spec:
  selector:
    app: rest-test2
  ports:
    - port: 80
      targetPort: 8080
