// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Data struct {
	ID    int    `json:"Id"`
	Phone string `json:"Phone"`
	Name  string `json:"Name"`
	Age   int    `json:"Age"`
}
